#!/bin/bash

#SBATCH --job-name="CONV_97"

#SBATCH --nodes=1

#SBATCH --gpus-per-node=a100:1 --constraint="dgx&ampere"       # specify gpu

#SBATCH --ntasks-per-node=1

#SBATCH --cpus-per-task=4       # cpu-cores per task (>1 if multi-threaded tasks)

#SBATCH --mem-per-cpu=150G               # memory per node (4G per cpu-core is default)

#SBATCH --time=24:00:00                                  # set runtime

#SBATCH -o ${SLURM_LOG_DIR}/CONV_97.out        # set log dir to home

# Source the configuration file
source Slurm/slurm_paths.conf

module load python/3.10
export PYTHONPATH=$(pwd)




# 3. Create or Set Up Environment

source env_new_emulator/bin/activate
echo "activated"

echo $PYTHONPATH
dir
cd $(pwd)


export NCCL_BLOCKING_WAIT=1 #Pytorch Lightning uses the NCCL backend for inter-GPU communication by default. Set this variable to avoid timeout errors.

# 8. Run Python
export HYDRA_FULL_ERROR=1
echo "Running python test.py ..."
srun python emulator/run.py experiment=Scaling_Experiments/97_Models/conv_97.yaml  seed=1234 # seed=3423

 

# 10. Experiment is finished

echo "Experiment $EXP_NAME is concluded."